---
sidebar: sidebar 
permalink: use/report-create.html 
keywords: BlueXP migration reports, volume reports 
summary: 'Grâce au service de rapports de migration BlueXP, vous pouvez identifier rapidement le nombre de fichiers, de répertoires, de liens symboliques, de liens physiques, la profondeur et l"étendue des arborescences des systèmes de fichiers, les fichiers les plus volumineux et bien plus encore dans votre paysage de stockage.' 
---
= Créer un rapport
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Vous pouvez créer un rapport sur les volumes qui indique le nombre de fichiers, de fichiers dans des répertoires, de liens symboliques, de liens physiques, de tailles de fichiers les plus importantes, et bien plus encore.

Chaque fois que vous créez un rapport, le service de rapports de migration BlueXP analyse le chemin et compile les données. En utilisant la même définition de rapport, vous pouvez avoir plusieurs instances de ce rapport.

Le service de rapports de migration BlueXP affiche les données par volume.

Vous ne pouvez générer qu'un seul rapport à la fois.

Vous pouvez également télécharger le rapport au format PDF.


TIP: Toutes les opérations de rapports de migration BlueXP sont répertoriées dans la chronologie BlueXP. Pour afficher le scénario, sélectionnez BlueXP *Settings* > *Timeline*.

.Étapes
. Dans le menu de navigation gauche de BlueXP, sélectionnez *Storage* > *migration Reports*.
. Sélectionnez *Créer un nouveau rapport*.
. Entrez un nom de rapport.
. Sélectionnez un environnement de travail dans la liste déroulante.
+
Seuls les environnements actifs et activés dans BlueXP apparaissent dans la liste des environnements de travail.

+

TIP: Le connecteur BlueXP doit avoir accès à la LIF de données du volume pour pouvoir accéder aux données.

+
Si vous souhaitez activer un environnement, reportez-vous à la section https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html#when-a-connector-is-required["Pour en savoir plus sur les connecteurs, consultez la documentation BlueXP"].

. À l'aide de l'icône *Search*, recherchez le volume à rapporter ou choisissez-le dans la liste.
. Sélectionnez le volume.
. Sélectionnez *Créer un rapport*.
+
Le service de rapports de migration BlueXP génère le rapport et le répertorie dans la liste des rapports.

. Pour afficher le rapport, sélectionnez *actions* ... Sur la droite et sélectionnez *Afficher le rapport*.
. Pour télécharger un fichier PDF du rapport, sélectionnez *actions* ... Et sélectionnez *Télécharger le rapport*.
. Pour générer une autre instance du même rapport, sélectionnez la ligne du rapport et, à droite, sélectionnez *Ajouter un rapport*.

