---
sidebar: sidebar 
permalink: get-started/intro.html 
keywords: how BlueXP migration reports works, reports, bluexp 
summary: 'Grâce au service de rapports de migration BlueXP, vous pouvez identifier rapidement le nombre de fichiers, de répertoires, de liens symboliques, de liens physiques, la profondeur et l"étendue des arborescences des systèmes de fichiers, les fichiers les plus volumineux et bien plus encore dans votre paysage de stockage.' 
---
= Découvrez les rapports sur la migration BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
Lorsque vous préparez le déplacement, la migration ou le clonage des données du système de fichiers, vous devez d'abord déterminer ce dont vous disposez. Grâce au service de rapports de migration BlueXP, vous pouvez identifier rapidement le nombre de fichiers, de répertoires, de liens symboliques, de liens physiques, la profondeur et l'étendue des arborescences des systèmes de fichiers, les fichiers les plus volumineux et bien plus encore dans votre paysage de stockage. Grâce à ces informations, vous saurez à l'avance que le processus que vous souhaitez utiliser peut gérer votre stock efficacement et avec succès.

Le service de rapports de migration BlueXP affiche des informations pour les environnements de travail NFS et AWS S3.



== Avantages des rapports de migration BlueXP

Le service de rapports de migration BlueXP offre les avantages suivants :

* Fournit un processus simple pour obtenir l'état de protection des données de votre environnement de travail
* Offre un paysage de stockage
* Réduction du temps passé à identifier des besoins de stockage supplémentaires




== Avantages des rapports de migration BlueXP

Grâce aux rapports de migration BlueXP, vous pouvez :

* Créer des rapports.
* Identifiez la façon dont les données ont changé d'une date de rapport à une autre à l'aide des tableaux de distribution des rapports.
* Activez les notifications par e-mail concernant la génération de rapports.
* Supprimer des rapports.




== Le coût

NetApp ne vous facture pas pour l'utilisation du service.



== Licences

Aucun fichier de licence NetApp n'est requis.
