---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'reports what"s new, bluexp' 
summary: 'Le nouveau service de rapports de migration BlueXP vous permet d"identifier rapidement le nombre de fichiers, de répertoires, de liens symboliques, de liens physiques, la profondeur et l"étendue des arborescences des systèmes de fichiers, les fichiers les plus volumineux et plus encore dans votre environnement de stockage.' 
---
= Quoi de neuf
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les nouveautés des rapports sur la migration BlueXP.



== 03 septembre 2023

Le service mis à jour de rapports de migration BlueXP fournit des mises à jour des données de rapport. Les rapports incluent désormais la capacité allouée.



== 02 juin 2023

Le nouveau service de rapports de migration BlueXP vous permet d'identifier rapidement le nombre de fichiers, de répertoires, de liens symboliques, de liens physiques, la profondeur et l'étendue des arborescences des systèmes de fichiers, les fichiers les plus volumineux et plus encore dans votre environnement de stockage.

Grâce à ces informations, vous saurez à l'avance que le processus que vous souhaitez utiliser peut gérer votre stock efficacement et avec succès.

link:https://docs.netapp.com/us-en/bluexp-reports/get-started/intro.html["En savoir plus sur les rapports de migration BlueXP"].
